/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1_olc1_201807088;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.io.FileOutputStream;
import java.io.StringReader;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import java.awt.Image;


/**
 *
 * @author Usuario
 */
public class Interfaz1 extends javax.swing.JFrame {

    public static String ruta, nombreArchivo, ER;
    public static String temporal = " ";
    public static LinkedList<String> nombreFollow = new LinkedList<>();
    public static LinkedList<String> nombretrans = new LinkedList<>();
    public static LinkedList<String> RutasArboles = new LinkedList<>();
    public static LinkedList<String> RutasSiguientes = new LinkedList<>();
    public static LinkedList<String> RutasTransiciones = new LinkedList<>();
    public static LinkedList<String> RutasAutomatas = new LinkedList<>();
    public static LinkedList<String> RutasAFND = new LinkedList<>();
    
    public static LinkedList<String> namesArboles = new LinkedList<>();
    public static LinkedList<String> nameSiguientes = new LinkedList<>();
    public static LinkedList<String> nameTransiciones = new LinkedList<>();
    public static LinkedList<String> nameAutomatas = new LinkedList<>();
    public static int contador =0;
    /**
     * Creates new form Interfaz1
     */
    public Interfaz1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        generar_automata = new javax.swing.JButton();
        Analizar = new javax.swing.JButton();
        Selector = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        entrada = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        guardar = new javax.swing.JMenuItem();
        guardar_como = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        jLabel1.setText("Salida:");

        generar_automata.setText("Generar Autómata");
        generar_automata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generar_automataMouseClicked(evt);
            }
        });
        generar_automata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_automataActionPerformed(evt);
            }
        });

        Analizar.setText("Analizar Entrada");
        Analizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnalizarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AnalizarMousePressed(evt);
            }
        });
        Analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalizarActionPerformed(evt);
            }
        });

        Selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arboles", "Siguientes", "Transiciones", "AFD", "AFND" }));
        Selector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SelectorMousePressed(evt);
            }
        });
        Selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectorActionPerformed(evt);
            }
        });

        jButton3.setText("Anterior");

        jButton4.setText("Siguiente");

        jLabel2.setText("Entrada:");

        entrada.setColumns(20);
        entrada.setRows(5);
        jScrollPane1.setViewportView(entrada);

        jMenu1.setText("Archivo");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenu4.setText("Abrir");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu4);

        guardar.setText("Guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardarMousePressed(evt);
            }
        });
        jMenu1.add(guardar);

        guardar_como.setText("Guardar como...");
        guardar_como.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardar_comoMousePressed(evt);
            }
        });
        jMenu1.add(guardar_como);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(generar_automata, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                                .addComponent(Analizar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Selector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Analizar)
                            .addComponent(generar_automata))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generar_automataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_automataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generar_automataActionPerformed

    private void SelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectorActionPerformed

    private void AnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalizarActionPerformed
        
    }//GEN-LAST:event_AnalizarActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        try {
            abrir();
        } catch (IOException ex) {
            Logger.getLogger(Interfaz1.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jMenu4MouseClicked

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked

    }//GEN-LAST:event_guardarMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        //Guardar();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void guardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMousePressed
        Guardar();// TODO add your handling code here:
    }//GEN-LAST:event_guardarMousePressed

    private void guardar_comoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardar_comoMousePressed
        guardarComo();        // TODO add your handling code here:
    }//GEN-LAST:event_guardar_comoMousePressed

    private void generar_automataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generar_automataMouseClicked
        
    }//GEN-LAST:event_generar_automataMouseClicked

    private void AnalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnalizarMouseClicked
            
    
    }//GEN-LAST:event_AnalizarMouseClicked

    private void AnalizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnalizarMousePressed
        try{
           String path = entrada.getText();
           Analizadores.Sintactico sintactico;
           sintactico = new Analizadores.Sintactico(new Analizadores.Lexico(new StringReader(path)));
           sintactico.parse();
        }catch(Exception e){
        }    
    }//GEN-LAST:event_AnalizarMousePressed

    private void SelectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectorMouseClicked
        
    }//GEN-LAST:event_SelectorMouseClicked

    private void SelectorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectorMousePressed
        String opcion = (String) Selector.getSelectedItem();
        contador = 0;
        if(null != opcion)switch (opcion) {
            case "Arboles":
                SelectArboles(contador);
                break;
            case "Siguientes":
                SelectSiguientes(contador);
                break;
            case "Transiciones":
                SelectTransiciones(contador);
                break;
            case "AFD":
                SelectAutomatas(contador);
                break;
            case "AFND":
                SelectAutomatasND(contador);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_SelectorMousePressed

    private void SelectArboles(int numero){
        if(!RutasArboles.isEmpty()){
            ImageIcon ImgIcon = new ImageIcon(RutasArboles.get(numero));
            Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(421,421,Image.SCALE_DEFAULT));
            Imagen.setIcon(icono);
            Imagen.setText(RutasArboles.get(numero));
        }
    }

    private void SelectSiguientes(int numero){
        if(!RutasSiguientes.isEmpty()){
            ImageIcon ImgIcon = new ImageIcon(RutasSiguientes.get(numero));
            Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(421,421,Image.SCALE_DEFAULT));
            Imagen.setIcon(icono);
            Imagen.setText(RutasSiguientes.get(numero));
        }
    }
    private void SelectTransiciones(int numero){
        if(!RutasTransiciones.isEmpty()){
            ImageIcon ImgIcon = new ImageIcon(RutasTransiciones.get(numero));
            Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(421,421,Image.SCALE_DEFAULT));
            Imagen.setIcon(icono);
            Imagen.setText(RutasTransiciones.get(numero));
        }
    }

    private void SelectAutomatas(int numero){
        if(!RutasAutomatas.isEmpty()){
            ImageIcon ImgIcon = new ImageIcon(RutasAutomatas.get(numero));
            Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(421,421,Image.SCALE_DEFAULT));
            Imagen.setIcon(icono);
            Imagen.setText(RutasAutomatas.get(numero));
        }
    }

    private void SelectAutomatasND(int numero){
        if(!RutasAFND.isEmpty()){
            ImageIcon ImgIcon = new ImageIcon(RutasAFND.get(numero));
            Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(421,421,Image.SCALE_DEFAULT));
            Imagen.setIcon(icono);
            Imagen.setText(RutasAFND.get(numero));
        }
    }
    
    
    private void abrir()  throws IOException {

        JFileChooser JFC = new JFileChooser();
        JFC.setFileFilter(new FileNameExtensionFilter(".olc",".er","olc","OLC"));
        int abrir = JFC.showDialog(null, "Abrir");
        if (abrir == JFileChooser.APPROVE_OPTION) {

            FileReader FR = null;
            BufferedReader BR = null;
            try {
                File archivo = JFC.getSelectedFile();
                String rut = JFC.getSelectedFile().getAbsolutePath();
                if (rut.endsWith(".OLC")|| rut.endsWith(".olc") || rut.endsWith(".er") ) {
                    FR = new FileReader(archivo);
                    BR = new BufferedReader(FR);
                    String linea;
                    ruta = "";
                    ruta = archivo.getAbsolutePath();
                    RutasArboles.clear();
                    RutasAFND.clear();
                    RutasSiguientes.clear();
                    RutasTransiciones.clear();
                    RutasAutomatas.clear();
                    Selector.setSelectedItem("Arboles");
                    Imagen.setIcon(null);
                    entrada.setText(null);
                    while ((linea = BR.readLine()) != null) {
                        entrada.setText(entrada.getText()+linea+"\n");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Archivo no soportado", "Ha ocurrido un error", JOptionPane.ERROR_MESSAGE);
                    abrir();
                }

            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } finally {
                try {
                    if (null != FR) {
                        FR.close();
                    }

                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }
    
    private void Guardar(){
            try {
            // Obtener el texto del JTextField
            String texto = entrada.getText();

            // Crear un objeto FileWriter para el archivo
            FileWriter fw = new FileWriter(ruta);

            // Crear un objeto BufferedWriter para escribir los datos en el archivo
            BufferedWriter bw = new BufferedWriter(fw);

            // Escribir el texto en el archivo
            bw.write(texto);

            // Cerrar el objeto BufferedWriter y el objeto FileWriter
            bw.close();
            fw.close();

            // Mostrar un mensaje de diálogo indicando que el archivo se ha guardado correctamente
            JOptionPane.showMessageDialog(this, "Archivo guardado correctamente.");

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
            
    private void guardarComo() {
    // Mostrar un JFileChooser para que el usuario seleccione la ubicación y el nombre del archivo
    JFileChooser jfc = new JFileChooser();
    jfc.setDialogTitle("Guardar como");
    jfc.setFileFilter(new FileNameExtensionFilter(".olc", "olc", "OLC"));

    int seleccion = jfc.showSaveDialog(this);

    if (seleccion == JFileChooser.APPROVE_OPTION) {
        File archivo = jfc.getSelectedFile();

        // Obtener la extensión del archivo seleccionado en el JFileChooser
        String extension = ((FileNameExtensionFilter) jfc.getFileFilter()).getExtensions()[0];

        // Si el archivo no tiene la extensión adecuada, añadir la extensión manualmente
        if (!archivo.getName().endsWith("." + extension)) {
            archivo = new File(archivo.getAbsolutePath() + "." + extension);
        }

        try {
            // Obtener el texto del JTextField
            String texto = entrada.getText();

            // Crear un objeto FileWriter para el archivo seleccionado
            FileWriter fw = new FileWriter(archivo);

            // Crear un objeto BufferedWriter para escribir los datos en el archivo
            BufferedWriter bw = new BufferedWriter(fw);

            // Escribir el texto en el archivo
            bw.write(texto);

            // Cerrar el objeto BufferedWriter y el objeto FileWriter
            bw.close();
            fw.close();

            // Mostrar un mensaje de diálogo indicando que el archivo se ha guardado correctamente
            JOptionPane.showMessageDialog(this, "Archivo guardado correctamente.");

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analizar;
    private javax.swing.JLabel Imagen;
    private javax.swing.JComboBox<String> Selector;
    private javax.swing.JTextArea entrada;
    private javax.swing.JButton generar_automata;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuItem guardar_como;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
