
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INVERBARRA = 23;
  public static final int GUION = 4;
  public static final int PUNTO = 9;
  public static final int PORC = 15;
  public static final int CONJUNTO = 2;
  public static final int LLAVEI = 6;
  public static final int BARRA = 12;
  public static final int LLAVED = 7;
  public static final int POR = 14;
  public static final int COMA = 21;
  public static final int COMILLASIMPLE = 22;
  public static final int EOF = 0;
  public static final int COMILLA = 20;
  public static final int ALFAMIN = 19;
  public static final int TODO = 25;
  public static final int VIR = 3;
  public static final int ALFAMAY = 18;
  public static final int error = 1;
  public static final int MQUE = 5;
  public static final int INTERR = 10;
  public static final int ASCII = 24;
  public static final int RAN = 17;
  public static final int ENTERO = 16;
  public static final int DPUNTOS = 8;
  public static final int MAS = 13;
  public static final int PTCOMA = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJUNTO",
  "VIR",
  "GUION",
  "MQUE",
  "LLAVEI",
  "LLAVED",
  "DPUNTOS",
  "PUNTO",
  "INTERR",
  "PTCOMA",
  "BARRA",
  "MAS",
  "POR",
  "PORC",
  "ENTERO",
  "RAN",
  "ALFAMAY",
  "ALFAMIN",
  "COMILLA",
  "COMA",
  "COMILLASIMPLE",
  "INVERBARRA",
  "ASCII",
  "TODO"
  };
}

